[2024.07.30] feat/#89 add posts hashtag >> 게시글 조회(해시태그 포함)
today-space/today-space pull request #107
Opened 2024-07-30 17:50 UTC by rohtable

## #️⃣ 연관된 이슈

> #89 
> Close #89 

## 📑 작업 내용
> 
- 게시글 조회(해시태그 포함)
- 해시태그별 최신 5개 글 조회

## 💭 리뷰 요구사항(선택)
>

2024-07-30 18:59 UTC, ysy56 requested changes
코드를 보면서 설계했던 부분과 조금 다른 것들이 있는 것 같아서 추후 의논해보아야 할 것 같습니다.

2024-07-30 18:59 UTC, ysy56 commented on src/main/java/com/complete/todayspace/domain/post/controller/PostController.java
> +    public ResponseEntity<?> getPostsByHashtag(@RequestParam("hashtagsName") List<String> hashtagsName) {
P2 : ResponseEntity<?> 이렇게 ?로 표시하는 것보다는 어떤 값이 반환되어야 하는지 직접 명시해주시는 게 좋습니다.
예시) ResponseEntity<DataResponseDto<List<PostResponseDto>>>

2024-07-30 18:59 UTC, ysy56 commented on src/main/java/com/complete/todayspace/domain/post/controller/PostController.java
> +    @GetMapping("/hashtags")
P3 : 처음 저희가 설계했던 api 명세서와 다른 것 같은데 맞나요..? 첫 설계는 아래와 같이 되어 있던 것으로 기억해서 확인부탁드립니다.
1. 전체 조회 v1/posts
2. 해시태그 검색 조회 v1/posts?hashtags=해시태그1

2024-07-31 02:45 UTC, rohtable commented on src/main/java/com/complete/todayspace/domain/post/controller/PostController.java
> +    public ResponseEntity<?> getPostsByHashtag(@RequestParam("hashtagsName") List<String> hashtagsName) {
api 수정으로 해당 부분은 제거되었습니다.

2024-07-31 02:45 UTC, rohtable commented on src/main/java/com/complete/todayspace/domain/post/controller/PostController.java
> +    @GetMapping("/hashtags")
api에 맞게 반영하여 수정하였습니다.

2024-07-31 03:01 UTC, ysy56 approved these changes
수정하신 것 확인했습니다!

2024-07-31 05:36 UTC, ryurbsgks5114 approved these changes
코드 확인하였고 문제 없는 것 같습니다.
코드 작성 하니라 고생하셨습니다.

2024-07-31 05:38 UTC, merged