[2024.07.24] feat/#45-edit-post
today-space/today-space pull request #55
Opened 2024-07-24 13:35 UTC by rohtable

## #️⃣ 연관된 이슈

> #45 
> Close #45 

## 📑 작업 내용
> - 게시글 수정

## 💭 리뷰 요구사항(선택)
> 코드 리뷰 외 수정 기능을 구현하면서 의문이 들어 확인 부탁드리겠습니다.
현재 커뮤니티 페이지에 게시글이 최신순으로 5개가 표시 됩니다.
최신순의 기준을 updatedAt으로 하다보니 수정된 글이 최상단으로 올라갑니다.
createdAt을 기준으로 최신순으로 하는 것이 맞을 것 같은데 의견 궁금합니다.
createdAt이 맞는 경우 조회 관련 수정하도록하겠습니다.

2024-07-24 13:48 UTC, ryurbsgks5114 requested changes
P2: 코드 리뷰 내용을 수정해서 올려주시고 다시 한번 슬랙 남겨주시면 확인하겠습니다.

2024-07-24 13:48 UTC, ryurbsgks5114 commented on src/main/java/com/complete/todayspace/global/exception/ErrorCode.java
> +    POST_NOT_FOUND(404,"해당 상품을 찾을 수 없습니다."),
P3: 매개변수 사이에 띄어쓰기만 해서 push 다시한번 해주세요

2024-07-24 13:48 UTC, ryurbsgks5114 commented on src/main/java/com/complete/todayspace/domain/post/service/PostService.java
P2: post를 찾을 때, orElse(null) 이 아닌 orElseThrow를 사용해서 Exception을 발생시켜야 할 것 같습니다.
null 값인 상태에서 update를 하게되면 DB에서 찾을 수 없는 값이라 오류가 날 것 같습니다.

2024-07-24 13:48 UTC, ysy56 approved these changes
전체적으로 깔끔하게 잘 작성하셨습니다. 2개 정도 코드리뷰를 달아놨는데 확인 해주시기 바랍니다!

2024-07-24 13:48 UTC, ysy56 commented on src/main/java/com/complete/todayspace/domain/post/controller/PostController.java
> +            @PathVariable Long postId,
P3 : post의 아이디는 1부터 시작하기 때문에 @Min(1) 최솟값이 1이라는 유효성 검사를 달아주시면 좋겠습니다.

2024-07-24 13:48 UTC, ysy56 commented on src/main/java/com/complete/todayspace/global/exception/ErrorCode.java
> +    NOT_OWNER_POST(403, "작성자만 변경할 수 있습니다."),
P3 : 이 부분 아마 Product 부분에 있을 겁니다. dev 브랜치 pull 받아서 확인 한 번 부탁드립니다.

2024-07-24 13:52 UTC, jdusw commented on src/main/java/com/complete/todayspace/global/exception/ErrorCode.java
> +    NOT_OWNER_POST(403, "작성자만 변경할 수 있습니다."),
P3 : 제가 보기에도 NOT_OWNER_PRODUCT과 동일한 내용 같아보이긴합니다

2024-07-24 14:40 UTC, rohtable commented on src/main/java/com/complete/todayspace/global/exception/ErrorCode.java
> +    NOT_OWNER_POST(403, "작성자만 변경할 수 있습니다."),
해당 부분 지우고 기존 product 코드 활용하였습니다.

2024-07-24 14:40 UTC, rohtable commented on src/main/java/com/complete/todayspace/global/exception/ErrorCode.java
> +    NOT_OWNER_POST(403, "작성자만 변경할 수 있습니다."),
해당 부분 지우고 기존 product 코드 활용하였습니다.

2024-07-24 14:40 UTC, rohtable commented on src/main/java/com/complete/todayspace/domain/post/controller/PostController.java
> +            @PathVariable Long postId,
@min 어노테이션 추가하였습니다.

2024-07-24 14:40 UTC, rohtable commented on src/main/java/com/complete/todayspace/domain/post/service/PostService.java
orElseThrow를 활용하여 코드 수정하였습니다.

2024-07-24 14:40 UTC, rohtable commented on src/main/java/com/complete/todayspace/global/exception/ErrorCode.java
> +    POST_NOT_FOUND(404,"해당 상품을 찾을 수 없습니다."),
수정 완료하였습니다.

2024-07-25 01:06 UTC, ryurbsgks5114 approved these changes

2024-07-25 01:06 UTC, merged