[2024.07.29] feat/#86 edit post image >>게시글 수정(기존 이미지 삭제, 추가)
today-space/today-space pull request #87
Opened 2024-07-29 16:50 UTC by rohtable

## #️⃣ 연관된 이슈

> #86 
> Close #86 

## 📑 작업 내용
> - 게시글 수정 시 기존 이미지 삭제, 추가 기능 구현

## 💭 리뷰 요구사항(선택)
> 
Postman 테스트 시, 등록과 같은 file 업로드 >> 추가
아래와 같이 Json data 로 이미지 아이디 입력 >> 삭제
{"content": "수정된 글","deleteImageIds": [imageId]}

2024-07-29 16:51 UTC, ysy56 approved these changes
수고하셨습니다!

2024-07-30 02:57 UTC, ryurbsgks5114 requested changes
P5: Setter는 지양하고 requestDto가 왔는데 requestDto를 변경하는 이유가 궁금합니다.

2024-07-30 03:31 UTC, rohtable commented
@ryurbsgks5114  requestDto를 변경하면 잠재적인 버그가 예상된다는 피드백을 받아 소스를 수정하였습니다.

2024-07-30 03:43 UTC, ryurbsgks5114 approved these changes

2024-07-30 03:45 UTC, merged